# Generated by Django 5.1.3 on 2024-12-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingprogress',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
