# Generated by Django 5.1.3 on 2024-12-09 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_readingprogress_progress_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='books',
            field=models.ManyToManyField(related_name='meetings', to='project.book'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='project.book'),
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progess', to='project.member'),
        ),
    ]
